### PR TITLE
[FLINK-32208] Remove dependency on flink-shaded from flink-connector-aws

### PR DESCRIPTION
**Pull request by snuyanzin**
Remove the dependency on [flink-shaded](https://issues.apache.org/jira/browse/FLINK-shaded) for [flink-connector-aws](https://github.com/apache/flink-connector-aws).

### CODE REVIEW

**Comment by snuyanzin** [comment]
hm... that's weird...
almost same command passes locally
```
mvn clean install -DskipTests -Dflink.convergence.phase=install -Pcheck-convergence -U -B \
-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120     \
-DaltDeploymentRepository=validation_repository::default::file:/tmp/flink-validation-deployment     \
-Dflink.version=1.16.1
```

**Comment by dannycranmer** [comment]
I have reproduced by running `mvn clean install -DskipTests -Pcheck-convergence -Dflink.version=1.17.0` directly on the `flink-connector-aws-kinesis-firehose` module. If running on the full project it passes, trying to root cause.

**Comment by dannycranmer** [comment]
Seems to fix by adding a managed dependency version to the project parent:

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.flink</groupId>
                <artifactId>flink-connector-base</artifactId>
                <version>${flink.version}</version>
            </dependency>
```

**Comment by dannycranmer** [comment]
I will push a new PR

**Pull request closed without merging**
