### PR TITLE
[FLINK-33194][Connectors/Kinesis] Remove dependency on Flink Shaded

### PR DESCRIPTION
**Pull request by Jiabao-Sun**
## Purpose of the change

[FLINK-33194] Remove dependency on Flink Shaded

## Verifying this change
This change is already covered by existing tests.

## Significant changes
*(Please check any boxes [x] if the answer is "yes". You can first publish the PR and check them afterwards, for convenience.)*
- [ ] Dependencies have been added or upgraded
- [ ] Public API has been changed (Public API is any class annotated with `@Public(Evolving)`)
- [ ] Serializers have been changed
- [ ] New feature has been introduced
  - If yes, how is this documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by Jiabao-Sun** [comment]
Hi @hlteoh37, please help review it when you have time.
Thanks.

**Review by z3d1k — APPROVED** [review]
LGTM

**Comment by Jiabao-Sun** [comment]
Hi @dannycranmer, could you help review this?
Thanks.

**Comment by Jiabao-Sun** [comment]
Hi @MartijnVisser, do you have time to help review it?
Thanks.

**Review by hlteoh37 — APPROVED** [review]
LGTM

**Pull request merged**
