### PR TITLE
[FLINK-33181] Allow a table definition can be used to read & write data to.

### PR DESCRIPTION
**Pull request by vtkhanh**
## Purpose of the change

Allow a table can be used as a source and sink when it's defined with both consumer & producer options. The ability is achieved by not verifying an option if it's *indicated* as consumer (by `scan.` prefix) or producer (by `sink.` prefix) option when creating a source/sink based on the table definition.

Example: following table definition can be used for both source & sink operators:

```
%flink.ssql(type=update)

DROP TABLE IF EXISTS `kds_input`;
CREATE TABLE `kds_input` (
`some_string` STRING,
`some_int` BIGINT,
`time` AS PROCTIME()
) WITH (
'connector' = 'kinesis',
'stream' = 'ExampleInputStream',
'aws.region' = 'us-east-1',
'scan.stream.initpos' = 'LATEST',
'sink.fail-on-error' = 'true',
'format' = 'csv'
);
```

## Verifying this change

This change added tests and can be verified as follows:
- *Added unit tests*

## Significant changes
*(Please check any boxes [x] if the answer is "yes". You can first publish the PR and check them afterwards, for convenience.)*
- [ ] Dependencies have been added or upgraded
- [ ] Public API has been changed (Public API is any class annotated with `@Public(Evolving)`)
- [ ] Serializers have been changed
- [ ] New feature has been introduced
  - If yes, how is this documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by vahmed-hamdy** [comment]
Hi  @vtkhanh, Could you please describe the use case more. It feels like an anti-pattern to use the same stream as source and sink. Kinesis Table API source and sink implementations were intentionally separated post 1.15.

**Comment by dannycranmer** [comment]
>  Kinesis Table API source and sink implementations were intentionally separated post 1.15.

No we kept them together, and supported the legacy configs for backwards compatibility.

**Review by dannycranmer — APPROVED** [review]
LGTM, thanks @vtkhanh

**Comment by dannycranmer** [comment]
Actions are failing due to a recent bug, will fix

**Comment by vtkhanh** [comment]
> Hi @vtkhanh, Could you please describe the use case more. It feels like an anti-pattern to use the same stream as source and sink. Kinesis Table API source and sink implementations were intentionally separated post 1.15.

I dont have a concrete usecase in production which a stream is used for both read from and write to within a Flink job. But we can find it useful in testing when we want to populate random data into a stream, and then read from it, by using one table definition, instead of 2 separate ones.

**Comment by vtkhanh** [comment]
> Actions are failing due to a recent bug, will fix

Merged your fix and updated the PR. Thanks for looking @dannycranmer.

**Pull request merged**
